-- MySQL Script generated by MySQL Workbench
-- 04/02/15 13:43:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pmsystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pmsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pmsystem` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `pmsystem` ;

-- -----------------------------------------------------
-- Table `pmsystem`.`usertype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmsystem`.`usertype` (
  `typeid` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`typeid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `typeid_UNIQUE` ON `pmsystem`.`usertype` (`typeid` ASC);


-- -----------------------------------------------------
-- Table `pmsystem`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmsystem`.`user` (
  `userid` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(64) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `usertype` INT NOT NULL,
  PRIMARY KEY (`userid`),
  CONSTRAINT `usertype`
    FOREIGN KEY (`usertype`)
    REFERENCES `pmsystem`.`usertype` (`typeid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `iduser_UNIQUE` ON `pmsystem`.`user` (`userid` ASC);

CREATE INDEX `usertype_idx` ON `pmsystem`.`user` (`usertype` ASC);


-- -----------------------------------------------------
-- Table `pmsystem`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmsystem`.`projects` (
  `projectid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `about` VARCHAR(2000) NOT NULL,
  `client` VARCHAR(100) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `deadline` DATETIME NOT NULL,
  `supervisor` INT NOT NULL,
  PRIMARY KEY (`projectid`),
  CONSTRAINT `supervisor`
    FOREIGN KEY (`supervisor`)
    REFERENCES `pmsystem`.`user` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `projectid_UNIQUE` ON `pmsystem`.`projects` (`projectid` ASC);

CREATE INDEX `supervisor_idx` ON `pmsystem`.`projects` (`supervisor` ASC);


-- -----------------------------------------------------
-- Table `pmsystem`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmsystem`.`notes` (
  `noteid` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(1000) NOT NULL,
  `userid` INT NOT NULL,
  PRIMARY KEY (`noteid`),
  CONSTRAINT `userid`
    FOREIGN KEY (`userid`)
    REFERENCES `pmsystem`.`user` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `noteid_UNIQUE` ON `pmsystem`.`notes` (`noteid` ASC);

CREATE INDEX `userid_idx` ON `pmsystem`.`notes` (`userid` ASC);


-- -----------------------------------------------------
-- Table `pmsystem`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmsystem`.`tasks` (
  `taskid` INT NOT NULL AUTO_INCREMENT,
  `task` VARCHAR(100) NOT NULL,
  `projectid` INT NOT NULL,
  `userid` INT NOT NULL,
  `deadline` DATETIME NULL,
  PRIMARY KEY (`taskid`),
  CONSTRAINT `projectid`
    FOREIGN KEY (`projectid`)
    REFERENCES `pmsystem`.`projects` (`projectid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `userid`
    FOREIGN KEY (`userid`)
    REFERENCES `pmsystem`.`user` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `taskid_UNIQUE` ON `pmsystem`.`tasks` (`taskid` ASC);

CREATE INDEX `projectid_idx` ON `pmsystem`.`tasks` (`projectid` ASC);

CREATE INDEX `userid_idx` ON `pmsystem`.`tasks` (`userid` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pmsystem`.`usertype`
-- -----------------------------------------------------
START TRANSACTION;
USE `pmsystem`;
INSERT INTO `pmsystem`.`usertype` (`typeid`, `type`) VALUES (DEFAULT, 'Admin');
INSERT INTO `pmsystem`.`usertype` (`typeid`, `type`) VALUES (DEFAULT, 'Supervisor');
INSERT INTO `pmsystem`.`usertype` (`typeid`, `type`) VALUES (DEFAULT, 'Employee');

COMMIT;

